// Generated by CoffeeScript 2.7.0
(function() {
  var $, autoRefresh, canvases, dataURItoBlob, drawText, files, fontStacks, formatValue, graph, imageInput, input, inputItems, makeStyle, readFiles, refresh, updateValue, valueDisplays,
    indexOf = [].indexOf;

  $ = function(sel) {
    return document.querySelector(sel);
  };

  inputItems = ['text', 'font', 'color', 'alpha', 'angle', 'space', 'size'];

  input = {};

  valueDisplays = {
    alpha: document.querySelector('#alpha-value'),
    angle: document.querySelector('#angle-value'),
    space: document.querySelector('#space-value'),
    size: document.querySelector('#size-value')
  };

  imageInput = $('#image');

  graph = $('#graph');

  refresh = $('#refresh');

  autoRefresh = $('#auto-refresh');

  files = [];

  canvases = [];

  dataURItoBlob = function(dataURI) {
    var arr, binStr, i, k, len, ref;
    binStr = atob((dataURI.split(','))[1]);
    len = binStr.length;
    arr = new Uint8Array(len);
    for (i = k = 0, ref = len - 1; (0 <= ref ? k <= ref : k >= ref); i = 0 <= ref ? ++k : --k) {
      arr[i] = binStr.charCodeAt(i);
    }
    return new Blob([arr], {
      type: 'image/png'
    });
  };

  readFiles = function() {
    if (!(files != null ? files.length : void 0)) {
      return;
    }
    graph.innerHTML = '';
    canvases = [];
    return Array.from(files).forEach(function(file) {
      var fileReader;
      fileReader = new FileReader();
      fileReader.onload = function() {
        var img;
        img = new Image();
        img.onload = function() {
          var canvas, ctx;
          canvas = document.createElement('canvas');
          canvas.width = img.width;
          canvas.height = img.height;
          ctx = canvas.getContext('2d');
          ctx.drawImage(img, 0, 0);
          canvases.push({
            canvas,
            ctx,
            img,
            name: file.name
          });
          canvas.addEventListener('click', function() {
            var blob, imageData, link, ref;
            link = document.createElement('a');
            link.download = (((ref = file.name) != null ? ref.replace(/(\.[^.]+)?$/, '') : void 0) || 'watermark') + '-marked.png';
            imageData = canvas.toDataURL('image/png');
            blob = dataURItoBlob(imageData);
            link.href = URL.createObjectURL(blob);
            graph.appendChild(link);
            return setTimeout(function() {
              link.click();
              return graph.removeChild(link);
            }, 100);
          });
          graph.appendChild(canvas);
          return drawText();
        };
        return img.src = fileReader.result;
      };
      return fileReader.readAsDataURL(file);
    });
  };

  makeStyle = function() {
    var match, ref;
    match = (ref = input.color.value) != null ? ref.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i) : void 0;
    if (match == null) {
      return 'rgba(29,155,240,' + input.alpha.value + ')';
    }
    return 'rgba(' + (parseInt(match[1], 16)) + ',' + (parseInt(match[2], 16)) + ',' + (parseInt(match[3], 16)) + ',' + input.alpha.value + ')';
  };

  fontStacks = {
    system: '-apple-system,"Helvetica Neue",Helvetica,Arial,"PingFang SC","Hiragino Sans GB","WenQuanYi Micro Hei",sans-serif',
    inter: '"Inter",-apple-system,"Helvetica Neue",Helvetica,Arial,"PingFang SC","Hiragino Sans GB","WenQuanYi Micro Hei",sans-serif',
    noto: '"Noto Sans SC","PingFang SC","Hiragino Sans GB","WenQuanYi Micro Hei",sans-serif',
    mono: '"SFMono-Regular",Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace'
  };

  formatValue = function(key, val) {
    switch (key) {
      case 'alpha':
        return Math.round(val * 100) + '%';
      case 'angle':
        return Math.round(val) + '°';
      case 'space':
        return val.toFixed(1) + 'x';
      case 'size':
        return val.toFixed(2) + 'x';
      default:
        return val;
    }
  };

  updateValue = function(key) {
    var display, val;
    display = valueDisplays[key];
    if (display == null) {
      return;
    }
    val = parseFloat(input[key].value);
    return display.textContent = formatValue(key, val);
  };

  drawText = function() {
    if (!canvases.length) {
      return;
    }
    canvases.forEach(function({canvas, ctx, img}) {
      var fontName, i, j, k, l, margin, ref, ref1, ref2, ref3, step, text, textSize, width, x, y;
      textSize = input.size.value * Math.max(15, (Math.min(canvas.width, canvas.height)) / 25);
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(img, 0, 0);
      ctx.save();
      ctx.translate(canvas.width / 2, canvas.height / 2);
      ctx.rotate(input.angle.value * Math.PI / 180);
      ctx.fillStyle = makeStyle();
      fontName = fontStacks[input.font.value] || fontStacks.system;
      ctx.font = 'bold ' + textSize + 'px ' + fontName;
      text = input.text.value || '内部水印';
      width = (ctx.measureText(text)).width;
      step = Math.sqrt((Math.pow(canvas.width, 2)) + (Math.pow(canvas.height, 2)));
      margin = (ctx.measureText('啊')).width;
      x = Math.ceil(step / (width + margin));
      y = Math.ceil((step / (input.space.value * textSize)) / 2);
      for (i = k = ref = -x, ref1 = x; (ref <= ref1 ? k <= ref1 : k >= ref1); i = ref <= ref1 ? ++k : --k) {
        for (j = l = ref2 = -y, ref3 = y; (ref2 <= ref3 ? l <= ref3 : l >= ref3); j = ref2 <= ref3 ? ++l : --l) {
          ctx.fillText(text, (width + margin) * i, input.space.value * textSize * j);
        }
      }
      return ctx.restore();
    });
  };

  imageInput.addEventListener('change', function() {
    var invalid, selected, validTypes;
    selected = Array.from(this.files || []);
    validTypes = ['image/png', 'image/jpeg', 'image/gif'];
    invalid = selected.filter(function(item) {
      var ref;
      return ref = item.type, indexOf.call(validTypes, ref) < 0;
    });
    files = selected.filter(function(item) {
      var ref;
      return ref = item.type, indexOf.call(validTypes, ref) >= 0;
    });
    if (invalid.length) {
      alert('已忽略非 png/jpg/gif 的文件');
    }
    if (!files.length) {
      return alert('请选择 png / jpg / gif 图片');
    }
    return readFiles();
  });

  autoRefresh.addEventListener('change', function() {
    if (this.checked) {
      return refresh.setAttribute('disabled', 'disabled');
    } else {
      return refresh.removeAttribute('disabled');
    }
  });

  autoRefresh.addEventListener('change', function() {
    if (this.checked) {
      return refresh.setAttribute('disabled', 'disabled');
    } else {
      return refresh.removeAttribute('disabled');
    }
  });

  inputItems.forEach(function(item) {
    var el;
    el = $('#' + item);
    input[item] = el;
    return el.addEventListener('input', function() {
      updateValue(item);
      if (autoRefresh.checked) {
        return drawText();
      }
    });
  });

  refresh.addEventListener('click', drawText);

  inputItems.forEach(function(item) {
    return updateValue(item);
  });

}).call(this);
